### ISSUE TITLE
Permission denied on running

### ISSUE THREAD

**Issue by takinekotfs** [takinekotfs/jupyter-cpp-kernel#1]
**Hardware info**
OS: Ubuntu 22.04LTS on WSL2

**Describe the bug**

```log
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/ipykernel/kernelbase.py", line 412, in dispatch_shell
    await result
  File "/usr/local/lib/python3.10/dist-packages/ipykernel/kernelbase.py", line 731, in execute_request
    reply_content = self.do_execute(
  File "/usr/local/lib/python3.10/dist-packages/jupyter_cpp_kernel/kernel.py", line 257, in do_execute
    p = self.create_jupyter_subprocess([self.master_path, binary_file.name] + magics['args'])
  File "/usr/local/lib/python3.10/dist-packages/jupyter_cpp_kernel/kernel.py", line 150, in create_jupyter_subprocess
    return RealTimeSubprocess(cmd,
  File "/usr/local/lib/python3.10/dist-packages/jupyter_cpp_kernel/kernel.py", line 25, in __init__
    super().__init__(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, stdin=subprocess.PIPE, bufsize=0)
  File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/tmp/tmphompk2ph.out'
```

**Comment by takinekotfs** [comment]
Fixed in https://github.com/takinekotfs/jupyter-cpp-kernel/commit/d86d1e17b9aa50f6270f0979e3b0cfb62fccf1b4
